class RPCConstants {
  static const String registerBusiness = 'register_business'; //
  static const String generateBusinessDependencies = 'generate_business_dependencies'; //
  static const String getRolePermissions = 'get_role_permissions'; //
  static const String upsertEmployeeRole = 'upsert_employee_role'; //
  static const String getSidebar = 'get_sidebar'; //
  static const String getNextSaleReturnCode = 'get_next_sale_return_code'; //
  static const String getNextItemCode = 'get_next_item_code'; //
  static const String getNextPurchaseReturnCode = 'get_next_purchase_return_code'; //
  static const String upsertItem = 'upsert_item'; //
  static const String adjustStock = 'adjust_stock'; //
  static const String createPurchase = 'create_purchase'; //
  static const String createSale = 'create_sale'; //
  static const String verifyUserPassword = 'verify_user_password';
  static const String bulkInsertItems = 'bulk_import_items';
  static const String settleSalePayment = 'settle_sale_payment'; //
  static const String settlePurchasePayment = 'settle_purchase_payment'; //
  static const String createSaleReturn = 'create_sale_return';
  static const String createPurchaseReturn = 'create_purchase_return';
  static const String getBusinessSummaries = 'get_business_summaries'; //
  static const String getPartyTransactionSummary = 'get_party_transaction_summary'; //
  static const String getDashboardData = 'get_dashboard_data'; //
  static const String updateSale = 'update_sale';
  static const String getSalesSummary = 'get_sales_summary';
  static const String getDailyTransactionSummary = 'get_daily_transactions_summary';
  static const String getPurchaseSummary = 'get_purchase_summary';
  static const String getTotalDuesSummary = 'get_total_dues_summary';
  static const String getEmployeeSalesSummary = 'get_employee_sales_summary_total';
  static const String getEmployeeSalesReport = 'get_employee_sales_report';
  static const String upsertExpense = 'upsert_expense';
  static const String upsertIncome = 'upsert_income';
  static const String archiveCustomer = 'archive_customer';
  static const String archiveSupplier = 'archive_supplier';
  static const String upsertSupplier = 'upsert_supplier';
  static const String upsertCustomer = 'upsert_customer';
  static const String reverseTransaction = 'reverse_transaction';
  static const String getChartOfAccountsTree = 'get_chart_of_accounts_tree';
  static const String archiveItem = 'archive_item';
  static const String reverseStockAdjustment = 'reverse_stock_adjustment';
  static const String getPromotionalPlanDetails = 'get_promotional_plan_details';
  static const String getPromotionalAddonDetails = 'get_promotional_addon_details';
  static const String getProfitAndLoss = 'get_profit_and_loss';
  static const String getCurrentFiscalPeriod = 'get_current_fiscal_period';
  static const String createQuote = 'create_quote';
  static const String updateQuote = 'update_quote';
  static const String getNextQuoteCode = 'get_next_quote_code';
  static const String getNextInvoiceCode = 'get_next_invoice_code';
  static const String createInvoice = 'create_invoice';

  static const String getNextPaymentCode = 'get_next_payment_code_preview';
  // static const String createPayment = 'create_payment';
  // static const String createPaymentAndUpdateInvoice = 'create_payment_and_update_invoice';
  static const String createCredit = 'create_credit_note';
  static const String createPaymentReceived = 'create_payment_received';
  static const String createRefund = 'create_refund';
  static const String editCreditNote = 'edit_credit_note';
  static const String updateInvoice = 'edit_invoice';
  static const String editPaymentReceived = 'edit_payment_received';
  static const String editCreditNoteAfterApplication = 'edit_credit_note_after_application';
  static const String deleteRefund = 'delete_refund';
  static const String deletePayment = 'delete_payment_received';
  static const String deleteInvoice = 'delete_invoice';
  static const String deleteCreditNote = 'delete_credit_note';
  static const String getNextCreditNoteCode = 'get_next_credit_note_code';
  //OODO: Develop these RPCs
  static const String getTimeSlots = 'get_time_slots';
  static const String getCurrentTimeSlot = 'get_current_time_slot';
  static const String createReservation = 'create_reservation';

}
