// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThHWrcNd2tUGQJjBEQs05YRBZg3uAcFc',
    appId: '1:141463328504:web:4ddd56e019d99baac68d0d',
    messagingSenderId: '141463328504',
    projectId: 'duxbe-application',
    authDomain: 'duxbe-application.firebaseapp.com',
    storageBucket: 'duxbe-application.appspot.com',
    measurementId: 'G-ZB8ZZFMBRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARYt2QECXvZRVyT5mPHT7LZMwcnNJl_B0',
    appId: '1:141463328504:android:828ee3ab12dedb7cc68d0d',
    messagingSenderId: '141463328504',
    projectId: 'duxbe-application',
    storageBucket: 'duxbe-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-rPOmmB_KPH545ZtKknZt2-t63xcCKY',
    appId: '1:141463328504:ios:74ece5763b9b1cd6c68d0d',
    messagingSenderId: '141463328504',
    projectId: 'duxbe-application',
    storageBucket: 'duxbe-application.appspot.com',
    iosBundleId: 'com.duxbe.business',
  );
}
