// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      case _:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXQkW2q_Ar641bW_XjJOi7GyeMNKDq1U',
    appId: '1:648584474232:web:4b0ad54e2f47f0b98d078d',
    messagingSenderId: '648584474232',
    projectId: 'han-pos-demo',
    authDomain: 'han-pos-demo.firebaseapp.com',
    storageBucket: 'han-pos-demo.appspot.com',
    measurementId: 'G-84G46PF3E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzNca6BjZXJcBOsT91z9M4uCypJCHsCo',
    appId: '1:648584474232:android:ccee636d9e174e758d078d',
    messagingSenderId: '648584474232',
    projectId: 'han-pos-demo',
    storageBucket: 'han-pos-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6OYhiqHPonNxLtxkO_OuAeJ2gOgJ_IU',
    appId: '1:648584474232:ios:1b67b9e8ced001f48d078d',
    messagingSenderId: '648584474232',
    projectId: 'han-pos-demo',
    storageBucket: 'han-pos-demo.appspot.com',
    iosBundleId: 'com.duxbe.business.dev',
  );
}
